### ISSUE TITLE
Create a Compatibility page for the re-design

### ISSUE THREAD

**Issue by ericpoirier** [EclipseFdn/sparkplug.eclipse.org#51]
Along with the redesign we are doing, we also need to create a Compatibility page.

We can implement this page once the WG is closer to launching this initiative.

**Comment by chrisguindon** [comment]
I would prefer that we focus our effort on finishing the re-design!

We will need a designer to mock this up first.

**Comment by chrisguindon** [comment]
@shanda-eclipse I was thinking that we might need design help but we might be able to leverage the work that we did for:
https://jakarta.ee/compatibility/

@fdesbiens Are you expecting different requirements than what we see on jakarta.ee?

**Comment by fdesbiens** [comment]
@chrisguindon No; we showed the Jakarta EE page to the Sparkplug steering committee and they were fine with the design. There are no specific requirements at this point.

**Comment by chrisguindon** [comment]
My question to you was not so much on the design but on the data that we are capturing and displaying to users. 

Here an example of the data file:
https://github.com/jakartaee/jakarta.ee/blob/src/data/compatible_products.yml

```
  - jakartaee_version: 8
    items:
    - title: Jakarta EE 8 Platform Compatible Products
      items:
      - name: Payara Server 
        vendor: Payara Services Limited
        image: '/images/compatible_products/payara_server.png'
        download: 'https://www.payara.fish/downloads/'
        versions:
        - version: 5.22.0
          compatibility: 'https://docs.payara.fish/enterprise/docs/5.22.0/jakartaee-certification/5.22.0/tck-results-full-5.22.0.html'
        - version: 5.23.0
          compatibility: 'https://docs.payara.fish/enterprise/docs/5.23.0/jakartaee-certification/5.23.0/tck-results-full-5.23.0.html'
```

Are you expecting Sparkplug to capture different data/links or will it be the same?
